version: '2.0'

services:
  nginx:
    image: nginx
    hostname: nginx
    container_name: nginx
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./volumes/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/conf.d:/etc/nginx/conf.d
      - ./volumes/logs:/var/log/nginx
    ports:
      - "6800:6800"
    networks:
      - rainsty

networks:
  rainsty:
    external:
      name: rainsty