version: '2.0'

services:
  canal_client:
    image: python:3.8.0
    restart: always
    hostname: flaskAppCompose
    container_name: flaskAppCompose
    ports:
      - 5000:5000
    volumes:
      - ./app.sh:/home/app.sh
      - ../flaskApp:/home/flaskApp
      - /etc/localtime:/etc/localtime
    command: bash /home/app.sh
