version: '2.0'

services:
  registry:
    image: registry
    restart: always
    hostname: registry
    container_name: registry
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    ports:
      - "5000:5000"
    volumes:
      - ./volumes:/auth
