version: '2.0'

services:
  gitbook:
    image: rainsty/gitbook:latest
    hostname: gitbook
    container_name: gitbook
    restart: always
    ports:
      - "8080:4000"
    volumes:
      - ../../../Docs:/gitbook
      - ./volumes/run.sh:/run.sh
    networks:
      - rainsty

networks:
  rainsty:
    external:
      name: rainsty
