version: '2'
services:
  zook01:
    image: zookeeper:3.4.13
    hostname: zook01
    container_name: zook01
    ports:
      - "8181:2181"
    volumes:
      - ./volumes/zookeeper/01/data:/data
      - ./volumes/zookeeper/01/datalog:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zook01:2888:3888 server.2=zook02:2888:3888 server.3=zook03:2888:3888
      ZOO_AUTOPURGE_SNAPRETAINCOUNT: 10
      ZOO_AUTOPURGE_PURGEINTERVAL: 5
    networks:
      - rainsty

  zook02:
    image: zookeeper:3.4.13
    hostname: zook02
    container_name: zook02
    ports:
      - "8182:2181"
    volumes:
      - ./volumes/zookeeper/02/data:/data
      - ./volumes/zookeeper/02/datalog:/datalog
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zook01:2888:3888 server.2=zook02:2888:3888 server.3=zook03:2888:3888
      ZOO_AUTOPURGE_SNAPRETAINCOUNT: 10
      ZOO_AUTOPURGE_PURGEINTERVAL: 5
    networks:
      - rainsty

  zook03:
    image: zookeeper:3.4.13
    hostname: zook03
    container_name: zook03
    ports:
      - "8183:2181"
    volumes:
      - ./volumes/zookeeper/03/data:/data
      - ./volumes/zookeeper/03/datalog:/datalog
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zook01:2888:3888 server.2=zook02:2888:3888 server.3=zook03:2888:3888
      ZOO_AUTOPURGE_SNAPRETAINCOUNT: 10
      ZOO_AUTOPURGE_PURGEINTERVAL: 5
    networks:
      - rainsty

networks:
  rainsty:
    external:
      name: rainsty