version: '2.0'

services:
  canal_client:
    image: python:3.8.0
    restart: always
    hostname: falconAppCompose
    container_name: falconAppCompose
    ports:
      - 5001:5000
    volumes:
      - ./app.sh:/home/app.sh
      - ../falconApp:/home/falconApp
      - /etc/localtime:/etc/localtime
    command: bash /home/app.sh
