version: '2'
services:
  sqlserver:
    image: exoplatform/sqlserver
    container_name: sqlserver
    hostname: sqlserver
    restart: always
    ports:
      - "1433:1433"
    environment:
      TZ: Asia/Shanghai
      SA_PASSWORD: "r123456."
      SQLSERVER_DATABASE: "rainsty"
      SQLSERVER_USER: "rainsty"
      SQLSERVER_PASSWORD: "r123456."
    volumes:
      - ./volumes/mssql:/var/opt/mssql
    networks:
      - rainsty

networks:
  rainsty:
    external:
      name: rainsty