version: '2'
services:
  kafka01:
    image: wurstmeister/kafka
    hostname: kafka01
    container_name: kafka01
    ports:
      - "8191:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:8191
      KAFKA_MESSAGE_MAX_BYTES: 10485670
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_ZOOKEEPER_CONNECT: zook01:2181,zook02:2181,zook03:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LOG_DIRS: "/kafka"
      KAFKA_CREATE_TOPICS: "rainsty:1:1"
    volumes:
      - ./volumes/kafka01/data:/kafka
      - ./volumes/kafka01/logs:/opt/kafka/logs
    networks:
      - rainsty

  kafka02:
    image: wurstmeister/kafka
    hostname: kafka02
    container_name: kafka02
    ports:
      - '8192:9092'
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:8192
      KAFKA_MESSAGE_MAX_BYTES: 10485670
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_ZOOKEEPER_CONNECT: zook01:2181,zook02:2181,zook03:2181
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LOG_DIRS: "/kafka"
    volumes:
      - ./volumes/kafka02/data:/kafka
      - ./volumes/kafka02/logs:/opt/kafka/logs
    networks:
      - rainsty

  kafka03:
    image: wurstmeister/kafka
    hostname: kafka03
    container_name: kafka03
    ports:
      - "8193:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:8193
      KAFKA_MESSAGE_MAX_BYTES: 10485670
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_ZOOKEEPER_CONNECT: zook01:2181,zook02:2181,zook03:2181
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LOG_DIRS: "/kafka"
    volumes:
      - ./volumes/kafka03/data:/kafka
      - ./volumes/kafka03/logs:/opt/kafka/logs
    networks:
      - rainsty

networks:
  rainsty:
    external:
      name: rainsty