version: '2.0'

services:
  canal_kafka1:
    image: 'bitnami/kafka:latest'
    ports:
      - '9192:9092'
    hostname: canal_kafka1
    container_name: canal_kafka1
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=canal_zoo1:2181,canal_zoo2:2181
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    external_links:
      - canal_zoo1
      - canal_zoo2
    networks:
      canal_zk_network:
        ipv4_address: 131.45.20.13

  canal_kafka2:
    image: 'bitnami/kafka:latest'
    ports:
      - '9193:9092'
    hostname: canal_kafka2
    container_name: canal_kafka2
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=canal_zoo1:2181,canal_zoo2:2181
      - KAFKA_BROKER_ID=2
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    external_links:
      - canal_zoo1
      - canal_zoo2
    networks:
      canal_zk_network:
        ipv4_address: 131.45.20.14

networks:
  canal_zk_network:
    external:
      name: canal_zk_network

