version: '2.0'

services:
  python:
    image: python:3.6.5
    hostname: python
    container_name: python
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./volumes/run.sh:/run.sh
      - ./volumes/requirements.txt:/requirements.txt
      - ./volumes/file:/file
    command: bash /run.sh
    networks:
      - rainsty

networks:
     rainsty:
       external:
         name: rainsty
