version: '2.0'

services:
  python:
    image: python:3.6.8
    hostname: python
    container_name: python
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./volumes/file:/file
      - ./volumes/pyenv:/opt/storm/pyenv
    command: tail -f /dev/null
    networks:
      - rainsty

networks:
  rainsty:
    external:
      name: rainsty

# sed -i "s/# alias ll='ls \$LS_OPTIONS -l'/alias ll='ls \$LS_OPTIONS -l'/g" /root/.bashrc & source /root/.bashrc
# pip install --upgrade pip -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
# pip install -r requirements.txt -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
